apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"fla-springboot-backend"},"name":"fla-springboot-backend","namespace":"qzaydf-dev"},"spec":{"replicas":2,"selector":{"io.kompose.service":"fla-springboot-backend"},"strategy":{"resources":{}},"template":{"metadata":{"creationTimestamp":null,"labels":{"io.kompose.service":"fla-springboot-backend"}},"spec":{"containers":[{"image":"","name":"fla-springboot-backend","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"250m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}}}],"restartPolicy":"Always"}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["fla-springboot-backend"],"from":{"kind":"ImageStreamTag","name":"fla-springboot-backend:dev","namespace":"qzaydf-tools"}},"type":"ImageChange"}]},"status":{}}
  creationTimestamp: "2020-07-06T17:05:20Z"
  generation: 58
  labels:
    app: API
  name: efiling-api
  namespace: qzaydf-dev
  resourceVersion: "1964236414"
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/qzaydf-dev/deploymentconfigs/efiling-api
  uid: dfbfb2da-bfaa-11ea-9656-0050568379a2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    io.kompose.service: efiling-api
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: "6"
        memory: 2Gi
      requests:
        cpu: "6"
        memory: 1Gi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: efiling-api
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: redis
            - name: NAVIGATION_BASE_URL
              value: "http://react-web-app-qzaydf-dev.pathfinder.gov.bc.ca/efiling"
            - name: KEYCLOAK_CREDENTIALS_SECRET
              value: 900f16db-df01-46b0-a0ee-65b5358ecf85
          envFrom:
            - configMapRef:
                name: cso-webservcie-map
            - secretRef:
                name: splunk-hec
            - configMapRef:
                name: spring-profiles-active
            - secretRef:
                name: keycloak
          image: >-
            docker-registry.default.svc:5000/qzaydf-tools/efiling-api@sha256:34ddaac539798f3b256ae81d388eeae30e38958cb145baf67a0b54aae37d6790
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: efiling-api
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - efiling-api
        from:
          kind: ImageStreamTag
          name: "efiling-api:dev"
          namespace: qzaydf-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/qzaydf-tools/efiling-api@sha256:34ddaac539798f3b256ae81d388eeae30e38958cb145baf67a0b54aae37d6790
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2020-07-27T17:53:51Z"
      lastUpdateTime: "2020-07-27T17:53:51Z"
      message: >-
        rollout of replication controller "fla-springboot-backend-48" was
        cancelled
      reason: RolloutCancelled
      status: "False"
      type: Progressing
    - lastTransitionTime: "2020-07-27T22:57:37Z"
      lastUpdateTime: "2020-07-27T22:57:37Z"
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 0
  observedGeneration: 58
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 0
