apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: modern-web-app-demo
  name: static-web-app-demo-running-on-nginx
  namespace: qzaydf-tools
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "static-web-app-demo-running-on-nginx:latest"
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: "react-web-app-demo-builder:latest"
        paths:
          - destinationDir: .
            sourcePath: /opt/app-root/output/robots.txt
          - destinationDir: ./efiling-demo
            sourcePath: /opt/app-root/output/.
    type: Image
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: "nginx-image-demo-runtime:latest"
      incremental: true
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: IUEKiA05P5i4Xeo1xFRQ6ePcw5d2bODNpJJM6QUD
      type: GitHub
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          centos/nginx-112-centos7@sha256:af171c38298e64664a9f999194480ce7e392858e773904df22f7585a1731ad0d
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: "react-web-app-demo-builder:latest"
        lastTriggeredImageID: >-
          docker-registry.default.svc:5000/qzaydf-tools/react-web-app-demo-builder@sha256:d4ba3613a6b0928b1cc3dac158c41d1159d0b4b31278f2fad40cd82566cd9930
      type: ImageChange
status:
  lastVersion: 0
