apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 36
  labels:
    app: Frontend
    application: modern-web-app
  name: react-web-app
  namespace: qzaydf-dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: react-web-app
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-web-app
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: >-
            docker-registry.default.svc:5000/qzaydf-tools/static-web-app-running-on-nginx@sha256:f7dc19089675ce325f2b9ade56635ad6580ed04e2dbb68bb7de343da86854f4b
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /efiling/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: static-web-app-running-on-nginx
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /efiling/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 70
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/app-root/src/efiling/frontend-env.js
              name: frontend-env-o2k3x
              readOnly: true
              subPath: frontend-env.js
            - mountPath: /opt/app-root/etc/nginx.default.d/
              name: efiling-frontend-c794k
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: frontend-env
          name: frontend-env-o2k3x
        - configMap:
            defaultMode: 420
            name: efiling-frontend
          name: efiling-frontend-c794k
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - static-web-app-running-on-nginx
        from:
          kind: ImageStreamTag
          name: "static-web-app-running-on-nginx:latest"
          namespace: qzaydf-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/qzaydf-tools/static-web-app-running-on-nginx@sha256:f7dc19089675ce325f2b9ade56635ad6580ed04e2dbb68bb7de343da86854f4b
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2020-07-23T15:58:37Z"
      lastUpdateTime: "2020-07-23T15:58:40Z"
      message: replication controller "react-web-app-31" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-07-28T18:58:15Z"
      lastUpdateTime: "2020-07-28T18:58:15Z"
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/qzaydf-tools/static-web-app-running-on-nginx@sha256:f7dc19089675ce325f2b9ade56635ad6580ed04e2dbb68bb7de343da86854f4b
        type: ImageChange
    message: image change
  latestVersion: 31
  observedGeneration: 36
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 0
