version: "3.7"
services:
  #############################################################################################
  ###                                 EFILING FRONTEND                                      ###
  #############################################################################################
  efiling-frontend:
    # need stdin_open:true because there is an issue with container being auto exited after startup with react-scripts 3.4.1
    stdin_open: true
    container_name: efiling-frontend
    build:
      context: ./src/frontend
      args:
        - SERVICE_NAME=efiling-frontend
    ports:
      - 3000:3000

  #############################################################################################
  ###                                 EFILING DEMO                                          ###
  #############################################################################################
  efiling-demo:
    # need stdin_open:true because there is an issue with container being auto exited after startup with react-scripts 3.4.1
    stdin_open: true
    container_name: efiling-demo
    build:
      context: ./src/frontend
      args:
        - SERVICE_NAME=efiling-demo
    ports:
      - 3001:3000

  #############################################################################################
  ###                           Efiling api backend app                                     ###
  #############################################################################################
  efiling-api:
    build:
      context: ./src/backend
      args:
        - SERVICE_NAME=efiling-api
        - MVN_PROFILE=${MVN_PROFILE}
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      - NAVIGATION_BASE_URL=http://localhost:3000/efiling
      - NAVIGATION_EXPIRYTIME=10
      - DEMO_MODE=${DEMO_MODE:-true}
      - CSO_ACCOUNTFACADE_USERNAME=${CSO_ACCOUNTFACADE_USERNAME}
      - CSO_ACCOUNTFACADE_PASSWORD=${CSO_ACCOUNTFACADE_PASSWORD}
      - CSO_ACCOUNTFACADE_URI=${CSO_ACCOUNTFACADE_URI}
      - CSO_ROLEREGISTRY_USERNAME=${CSO_ROLEREGISTRY_USERNAME}
      - CSO_ROLEREGISTRY_PASSWORD=${CSO_ROLEREGISTRY_PASSWORD}
      - CSO_ROLEREGISTRY_URI=${CSO_ROLEREGISTRY_URI}
      - CSO_LOOKUPFACADE_USERNAME=${CSO_LOOKUPFACADE_USERNAME}
      - CSO_LOOKUPFACADE_PASSWORD=${CSO_LOOKUPFACADE_PASSWORD}
      - CSO_LOOKUPFACADE_URI=${CSO_LOOKUPFACADE_URI}
      - BCEID_LOOKUP_USERNAME=${BCEID_LOOKUP_USERNAME}
      - BCEID_LOOKUP_PASSWORD=${BCEID_LOOKUP_PASSWORD}
      - BCEID_LOOKUP_URI=${BCEID_LOOKUP_URI}
    networks:
      - fisu-net

  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always
    networks:
      - fisu-net

  #############################################################################################
  ###                             RABBIT MQ SERVER                                          ###
  #############################################################################################
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - fisu-net

  #############################################################################################
  ###                             KEYCLOAK POSTGRES                                         ###
  #############################################################################################

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  #############################################################################################
  ###                                        KEYCLOAK                                       ###
  #############################################################################################

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8081:8080
    depends_on:
      - postgres

volumes:
  data-redis:
  data-rabbit:
  postgres_data:
    driver: local

networks:
  fisu-net:
    driver: "bridge"
