version: "3.7"
services:

  #############################################################################################
  ###                           Efiling api backend app                                     ###
  #############################################################################################
  efiling-api:
    container_name: efiling-api
    hostname: efiling-api
    build:
      context: ./src/backend
      dockerfile: Dockerfile.efiling-api
      args:
        - MVN_PROFILE=${MVN_PROFILE:-efiling-api-demo}
        - SKIP_TESTS=true
        - STARTERS_V=v0.1.8