version: "3.7"
services:
  #############################################################################################
  ###                                 EFILING FRONTEND                                      ###
  #############################################################################################
  efiling-frontend:
    # need stdin_open:true because there is an issue with container being auto exited after startup with react-scripts 3.4.1
    stdin_open: true
    container_name: efiling-frontend
    build:
      context: ./src/frontend
      args:
        - SERVICE_NAME=efiling-frontend
    ports:
      - 3000:3000

  #############################################################################################
  ###                                 EFILING DEMO                                          ###
  #############################################################################################
  efiling-demo:
    # need stdin_open:true because there is an issue with container being auto exited after startup with react-scripts 3.4.1
    stdin_open: true
    container_name: efiling-demo
    build:
      context: ./src/frontend
      args:
        - SERVICE_NAME=efiling-demo
    ports:
      - 3001:3000

  #############################################################################################
  ###                           Efiling api backend app                                     ###
  #############################################################################################
  efiling-api:
    build:
      context: ./src/backend
      args:
        - SERVICE_NAME=efiling-api
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin
      - NAVIGATION_BASE_URL=http://localhost:3000/efiling
      - NAVIGATION_EXPIRYTIME=10
      - CSO_ACCOUNTFACADE_USERNAME=${CSO_ACCOUNTFACADE_USERNAME}
      - CSO_ACCOUNTFACADE_PASSWORD=${CSO_ACCOUNTFACADE_PASSWORD}
      - CSO_ACCOUNTFACADE_URI=${CSO_ACCOUNTFACADE_URI}
    networks:
      - fisu-net

  #############################################################################################
  ###                                 REDIS SERVER                                          ###
  #############################################################################################
  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always
    networks:
      - fisu-net

  #############################################################################################
  ###                             RABBIT MQ SERVER                                          ###
  #############################################################################################
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - fisu-net

volumes:
  data-redis:
  data-rabbit:

networks:
  fisu-net:
    driver: "bridge"
