openapi: 3.0.0
info:
  version: 0.3.0
  title: jag-efiling-api
  description: Efiling api
servers:
  - url: "http://localhost:8080"
tags:
  - name: submission
    description: Submission Api
security:
  - bearerAuth: []
paths:
  "/submission/documents":
    post:
      summary: Initial documents upload
      operationId: UploadSubmissionDocuments
      tags:
        - submission
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: File successfully received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadSubmissionDocumentsResponse"
  "/submission/{submissionId}":
    get:
      summary: Get user detail for a given submission
      operationId: GetSubmission
      tags:
        - submission
      parameters:
        - $ref: "#/components/parameters/submissionId"
        - $ref: "#/components/parameters/xTransactionId"
      responses:
        "200":
          description: Config found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSubmissionResponse"
        "404":
          description: Config not foun
  "/submission/{submissionId}/generateUrl":
    post:
      summary: Generates a secure URL for e-filing submission
      operationId: GenerateUrl
      tags:
        - submission
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/submissionId"
      requestBody:
        description: requested parameters to generate a url
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateUrlRequest"
      responses:
        "200":
          description: File successfully received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateUrlResponse"
        "403":
          description: Request does not meet the required criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EfilingError"
  "/submission/{submissionId}/submit-filing-package":
    post:
      summary: Submit the filing package to cso
      operationId: Submit
      tags:
        - submission
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/submissionId"
      requestBody:
        description: filing submit parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitFilingPackageRequest"
      responses:
        "200":
          description: Filing package succesfully submitted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitFilingPackageResponse"
        "403":
          description: Request does not meet the required criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EfilingError"
  "/submission/{submissionId}/filing-package":
    get:
      summary: Get filing package information
      operationId: GetSubmissionFilingPackage
      tags:
        - submission
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/submissionId"
      responses:
        "200":
          description: Filing Package Information found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilingPackage"
        "404":
          description: Filing Package Information not found
  "/submission/{submissionId}/document/{filename}":
    get:
      summary: Get document by name
      operationId: GetSubmissionDocument
      tags:
        - submission
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/submissionId"
        - name: filename
          in: path
          description: A document name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Filing Package Information found
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          description: Document not found
  "/csoAccount":
    post:
      summary: Create a CSO account
      operationId: CreateAccount
      description: In order to create an account, an item with type BCEID is required in the accounts field.
      tags:
        - account
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
      requestBody:
        description: cso account details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDetails"
      responses:
        "201":
          description: Account Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    xTransactionId:
      name: X-Transaction-Id
      in: header
      schema:
        type: string
        format: uuid
      required: true
      description: A unique Transaction Id generated by FilingHub clients
    submissionId:
      name: submissionId
      in: path
      description: A submission id
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Account:
      type: object
      description: represents a user account
      properties:
        type:
          type: string
          enum: [BCEID, CSO]
          description: the account type
        identifier:
          type: string
          description: the account identifier
    DocumentProperties:
      type: object
      description: Submission Metadata used to describe the submission that will be e-filled
      required:
        - type
        - name
      properties:
        name:
          type: string
          description: the name of the document
        type:
          type: string
          description: the submission type
    Document:
      required:
        - description
        - statutoryFeeAmount
      type: object
      description: A Efiling Document
      allOf:
        - $ref: "#/components/schemas/DocumentProperties"
      properties:
        description:
          type: string
          description: the description of the document
        statutoryFeeAmount:
          type: number
          description: statutory fee amount
        mimeType:
          type: string
          description: File mime type
    EfilingError:
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
    GenerateUrlRequest:
      description: details about the required transaction
      required:
        - clientApplication
        - navigation
        - documentProperties
      properties:
        clientApplication:
          $ref: "#/components/schemas/ClientApplication"
        filingPackage:
          $ref: "#/components/schemas/InitialPackage"
        navigation:
          $ref: "#/components/schemas/Navigation"
    GenerateUrlResponse:
      description: A temporary url for uploading submission
      properties:
        expiryDate:
          type: integer
          format: int64
        efilingUrl:
          type: string
    GetSubmissionResponse:
      type: object
      required:
        - userDetails
        - navigation
      properties:
        userDetails:
          $ref: "#/components/schemas/UserDetails"
        navigation:
          $ref: "#/components/schemas/Navigation"
    Navigation:
      required:
        - success
        - error
        - cancel
      properties:
        success:
          $ref: "#/components/schemas/Redirect"
        error:
          $ref: "#/components/schemas/Redirect"
        cancel:
          $ref: "#/components/schemas/Redirect"
    InitialPackage:
      type: object
      description: A filing package can contain one or multiple documents that have or are being submitted electronically for new or existing court file.
      properties:
        documents:
          type: array
          items:
            $ref: "#/components/schemas/DocumentProperties"
        court:
          $ref: "#/components/schemas/CourtBase"
    FilingPackage:
      type: object
      description: A filing package can contain one or multiple documents that have or are being submitted electronically for new or existing court file.
      required:
        - submissionFeeAmount
        - documents
      properties:
        submissionFeeAmount:
          type: number
          description: Package submission fee.
        court:
          $ref: "#/components/schemas/Court"
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
    CourtBase:
      type: object
      description: "Court related information"
      required:
        - location
        - level
        - courtClass
        - division
      properties:
        location:
          type: string
          description: the court location
        level:
          type: string
          description: the court level
        courtClass:
          type: string
          description: the court class
        division:
          type: string
          description: the court division
        fileNumber:
          type: string
          description: the file number if case already exists
        participatingClass:
          type: string
    Court:
      type: object
      description: "Court related information"
      allOf:
        - $ref: "#/components/schemas/CourtBase"
      required:
        - locationDescription
      properties:
        locationDescription:
          type: string
          description: the court location description
        levelDescription:
          type: string
          description: the court location description
        classDescription:
          type: string
          description: the court location description
    Redirect:
      required:
        - url
      properties:
        url:
          type: string
    ClientApplication:
      type: object
      required:
        - displayName
        - type
      properties:
        displayName:
          type: string
        type:
          type: string
          description: the client Court Services Online Application Code
    UploadSubmissionDocumentsResponse:
      description: represents upload document response
      type: object
      required:
        - submissionId
      properties:
        submissionId:
          type: string
          format: uuid
          description: a unique identifier for the submission
        received:
          type: number
          description: the number of document received
    UserDetails:
      description: represents a user submitting a filing package
      type: object
      required:
        - universalId
        - firstName
        - lastName
        - middleName
        - email
      properties:
        universalId:
          type: string
          format: uuid
          description: the user universal identifier
        firstName:
          type: string
          description: the user first name
        lastName:
          type: string
          description: the user last name
        middleName:
          type: string
          description: the user middle name
        email:
          type: string
          description: the user email address
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/Account"
    SubmitFilingPackageRequest:
      description: submit filing package
      type: object
      required:
        - isRushOrder
      properties:
        isRushOrder:
          type: boolean
          description: the request is a rush order
    SubmitFilingPackageResponse:
      description: result of submit filing package
      type: object
      required:
        - transactionId
        - acknowledge
      properties:
        transactionId:
          type: number
          description: the transaction id returned from cso
        acknowledge:
          type: date
          description: date transaction was returned
