apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"description":"Exposes
      and load balances the application
      pods"},"labels":{"app":"fla-springboot-backend","template":"meta-service"},"name":"fla-springboot-backend","namespace":"qzaydf-dev"},"spec":{"ports":[{"name":"web","port":80,"targetPort":8080}],"selector":{"deploymentconfig":"fla-springboot-backend"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  labels:
    app: fla-springboot-backend
    template: meta-service
  name: fla-springboot-backend
  namespace: qzaydf-dev
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: fla-springboot-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
