apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-web-app
    application: modern-web-app
  name: react-web-app
  namespace: qzaydf-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: react-web-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
