apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  labels:
    app: fla-springboot-backend
    template: master-build-pipeline
  name: fla-springboot-backend
  namespace: qzaydf-tools
spec:
  completionDeadlineSeconds: 1800
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "fla-springboot-backend:latest"
  postCommit: {}
  resources:
    limits:
      cpu: "4"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 1Gi
  runPolicy: Serial
  source:
    contextDir: src/backend/efiling-api
    git:
      ref: master
      uri: "https://github.com/bcgov/jag-file-submission"
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: MAVEN_MIRROR_URL
          value: "http://nexus:8081/repository/fla-backend-group/"
      from:
        kind: ImageStreamTag
        name: "java:8"
        namespace: openshift
    type: Source
  triggers: []
status:
  lastVersion: 0
