apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: modern-web-app
  name: react-web-app-builder
  namespace: qzaydf-tools
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "react-web-app-builder:latest"
  postCommit: {}
  resources:
    limits:
      cpu: "4"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 1Gi
  runPolicy: Serial
  source:
    contextDir: src/frontend/efiling-frontend
    git:
      ref: master
      uri: "https://github.com/bcgov/jag-file-submission"
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: OUTPUT_DIR
          value: build
        - name: YARN_ENABLED
          value: "true"
      from:
        kind: ImageStreamTag
        name: "web-app-s2i-image:latest"
      incremental: true
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: LdiwSKDDNDx2M6OIKm1skedR36PLyrr2RCYqct24
      type: GitHub
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          nodeshift/centos7-s2i-web-app@sha256:7b806bbc6d66f9e84c6209791b601660acdd96c85fe0ebd27dfc2a1a349cabae
      type: ImageChange
status:
  lastVersion: 0
