apiVersion: v1
kind: Template
labels:
  template: static-web-app-running-on-nginx-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: static-web-app-running-on-nginx-template
    description: |-
      This is a template for the react web app builder template.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: static-web-app-running-on-nginx-template
parameters:
  - description: The OpenShift Namespace prefix.
    displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
    name: namespacePrefix
    required: true
    value:
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        # TODO REMOVE TEST
        application: static-web-app-running-on-nginx-test
      name: static-web-app-running-on-nginx-test
      namespace: "${namespacePrefix}-tools"
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        application: modern-web-app
        # TODO REMOVE TEST
      name: static-web-app-running-on-nginx-test
      namespace: qzaydf-tools
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          # TODO REMOVE TEST
          name: "static-web-app-running-on-nginx-test:latest"
      postCommit: {}
      resources: {}
      runPolicy: Serial
      #source:
      #images:
      #- as: null
      #from:
      #kind: ImageStreamTag
      #name: "react-web-app-builder-test:latest"
      # TODO IMPLEMENT MOUNTS
      #paths:
      #- destinationDir: .
      #sourcePath: /opt/app-root/output/robots.txt
      #- destinationDir: ./efiling
      #sourcePath: /opt/app-root/output/.
      #type: Image
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "nginx-image-runtime:latest"
          incremental: true
        type: Source
      successfulBuildsHistoryLimit: 5
      triggers:
        - github:
            secret: LdiwSKDDNDx2M6OIKm1skedR36PLyrr2RCYqct24
          type: GitHub
        - type: ConfigChange
        - imageChange:
            lastTriggeredImageID: >-
              centos/nginx-112-centos7@sha256:af171c38298e64664a9f999194480ce7e392858e773904df22f7585a1731ad0d
          type: ImageChange
    status:
      lastVersion: 0
