server:
  port: ${SERVER_PORT:8080}
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin}
  cache:
    redis:
      time-to-live: ${CACHE_TTL:600000}
jag:
  efiling:
    navigation:
      baseUrl: ${NAVIGATION_BASE_URL:https://httpbin.org/}
    account:
      client:
        userName: ${CSO_ACCOUNTFACADE_USERNAME}
        password: ${CSO_ACCOUNTFACADE_PASSWORD}
        uri: ${CSO_ACCOUNTFACADE_URI:http://localhost:8091}

    role:
      client:
        userName: ${CSO_ACCOUNTFACADE_USERNAME}
        password: ${CSO_ACCOUNTFACADE_PASSWORD}
        uri: ${CSO_ROLEREGISTRY_URI:http://localhost:8091}

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
opentracing:
  jaeger:
    service-name: efilingApi
    enabled: TRUE
    udp-sender:
      host: localhost
