apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: efiling-api
    template: efiling-pipeline-template
  name: efiling-api-pipeline
  namespace: qzaydf-tools
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: src/backend
    git:
      ref: master
      uri: "https://github.com/bcgov/jag-file-submission"
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: APP_NAME
          value: efiling-api
        - name: LIFECYCLE_WEBHOOK
        - name: GIT_SOURCE_URL
          value: "https://github.com/bcgov/jag-file-submission"
        - name: GIT_SOURCE_REF
          value: master
        - name: GIT_CONTEXT_DIR
          value: src/backend
        - name: CHECKOUT_SRC
          value: "${gitCheckoutRequired}"
        - name: JENKINS_POD
          value: maven
        - name: TOOLS_NAMESPACE
          value: qzaydf-tools
        - name: DEV_NAMESPACE
          value: qzaydf-dev
        - name: TEST_NAMESPACE
          value: qzaydf-test
        - name: PROD_NAMESPACE
          value: qzaydf-prod
        - name: ROUTE_TYPE
          value: private
      jenkinsfile: |
        try {
            node("${JENKINS_POD}") {

                // Build Image
                stage("Build ${APP_NAME}") {
                    openshift.withCluster() {
                        openshift.withProject() {
                            sh 'oc start-build ${APP_NAME} -n ${TOOLS_NAMESPACE} --wait' 
                        }
                    }
                }

                // Tag Image for Dev
                stage('Promote to DEV') {
                    openshift.withCluster() {
                        sh "echo Tagging image for DEV"
                        openshift.tag("${APP_NAME}:latest", "${APP_NAME}:dev")
                    }
                }

                stage("Deploy to DEV") {
                    openshift.withCluster() {
                        openshift.withProject() {
                            sh 'echo Wait for Demo app to rollout completely.'
                            sh 'oc rollout status -n ${DEV_NAMESPACE} dc/${APP_NAME} --watch'
                        }
                    }
                }
                
                // Tag Image for Test
                stage('Promote to TEST') {
                    openshift.withCluster() {
                        sh "echo Tagging image for TEST"
                        openshift.tag("${APP_NAME}:latest", "${APP_NAME}:test")
                    }
                }
                
                stage("Deploy to TEST") {
                    openshift.withCluster() {
                        openshift.withProject() {
                            sh 'echo Wait for Demo app to rollout completely.'
                            sh 'oc rollout status -n ${TEST_NAMESPACE} dc/${APP_NAME} --watch'
                        }
                    }
                }

            }

        } catch (err) {
            echo "in catch block"
            currentBuild.result = 'FAILURE'
            env.ERR = "${err}"
            node {
                sh "curl -XPOST '${LIFECYCLE_WEBHOOK}' -H 'Content-type: application/json' --data '{\"username\":\"The Pipe Lion\",\"icon_emoji\":\":lion_face:\",\"text\": \"${APP_NAME} Pipeline Failure - ${ERR}\"}'"
            }
            echo "Caught: ${err}"
            throw err
        }
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
      type: GitHub
status:
  lastVersion: 0
