name: Cucumber Tests

on:
  push:
    branches: [master, qa-cucumber-fail]

jobs:
  cucumber-tests:
    name: Runs cucumber-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Using shell script to install Google Chrome
      - name: Install Google Chrome
        run: |
          chmod +x ./scripts/installChrome.sh
           ./scripts/installChrome.sh

      # Build Docker and Run Tests
      - name: build docker
        run: |
          sleep 10
          EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET=${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}} KEYCLOAK_REALM=${{secrets.KEYCLOAK_REALM}} KEYCLOAK_URL=${{secrets.KEYCLOAK_URL}} EFILING_DEMO_KEYCLOAK_REALM=${{secrets.EFILING_DEMO_KEYCLOAK_REALM}} EFILING_DEMO_KEYCLOAK_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} KEYCLOAK_AUTH_SERVER_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} docker-compose up -d redis sftp clamav efiling-demo efiling-frontend
          EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET=${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}} KEYCLOAK_REALM=${{secrets.KEYCLOAK_REALM}} KEYCLOAK_URL=${{secrets.KEYCLOAK_URL}} EFILING_DEMO_KEYCLOAK_REALM=${{secrets.EFILING_DEMO_KEYCLOAK_REALM}} EFILING_DEMO_KEYCLOAK_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} KEYCLOAK_AUTH_SERVER_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} CSO_DEBUG_ENABLED=false KEYCLOAK_SSL_REQUIRED=none KEYCLOAK_RESOURCE=efiling-api docker-compose build efiling-api
          EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET=${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}} KEYCLOAK_REALM=${{secrets.KEYCLOAK_REALM}} KEYCLOAK_URL=${{secrets.KEYCLOAK_URL}} EFILING_DEMO_KEYCLOAK_REALM=${{secrets.EFILING_DEMO_KEYCLOAK_REALM}} EFILING_DEMO_KEYCLOAK_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} KEYCLOAK_AUTH_SERVER_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} CSO_DEBUG_ENABLED=false KEYCLOAK_SSL_REQUIRED=none KEYCLOAK_RESOURCE=efiling-api docker-compose up efiling-api &disown
          sleep 30
          mvn verify -Pconfig -DBCEID_USERNAME=${{secrets.BCEID_USERNAME}} -DBCEID_PASSWORD=${{secrets.BCEID_PASSWORD}} -DEFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET=${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}} -DKEYCLOAK_URL=${{secrets.KEYCLOAK_URL}}/realms/${{secrets.KEYCLOAK_REALM}}/protocol/openid-connect/token -DBASE_URI=${{secrets.BASE_URI}} -DBROWSER=${{secrets.BROWSER}} -f tests/pom.xml

      # Upload Spark report for debugging purposes
      - name: Upload Spark report for debugging purposes
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-spark-report
          path: ./tests/test-output/extent/Spark/Index.html

      # Upload Cucumber JSON for debugging purposes
      - name: Upload Cucumber JSON for debugging purposes
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-json-report
          path: ./tests/target/cucumber-reports/CucumberTestReport.json
