name: Cucumber Tests

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  cucumber-tests:
    name: Runs cucumber-tests
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git repo.
        uses: actions/checkout@v2

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - name: Pull the previously cached images.
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*', '**/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
            ${{ runner.os }}-

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Docker Images
        env:
          DOCKER_BUILDKIT: '1'
          CSO_DEBUG_ENABLED: 'false'
        run: |
          docker-compose build --parallel efiling-demo efiling-frontend efiling-api

      - name: Standup Docker Pods
        run: |
          docker-compose up -d redis sftp clamav efiling-demo efiling-frontend efiling-api &disown
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080/actuator/health); do
            printf 'efiling-api not up'
            sleep 5
          done
          printf 'up'

      - name: Running Integration Tests
        env:
          KEYCLOAK_CREDENTIALS_SECRET: ${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}}
          KEYCLOAK_REALM: ${{secrets.KEYCLOAK_REALM}}
          KEYCLOAK_URL: ${{secrets.KEYCLOAK_URL}}
          REACT_APP_KEYCLOAK_REALM: ${{secrets.EFILING_DEMO_KEYCLOAK_REALM}}
          REACT_APP_KEYCLOAK_URL: ${{secrets.EFILING_DEMO_KEYCLOAK_URL}}
          KEYCLOAK_AUTH_SERVER_URL: ${{secrets.EFILING_DEMO_KEYCLOAK_URL}}
          CSO_DEBUG_ENABLED: 'false'
          KEYCLOAK_SSL_REQUIRED: 'none'
          KEYCLOAK_RESOURCE: 'efiling-api'
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt install ./google-chrome-stable_current_amd64.deb
          mvn verify -Pconfig -DBCEID_USERNAME=${{secrets.BCEID_USERNAME}} -DBCEID_PASSWORD=${{secrets.BCEID_PASSWORD}} -DEFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET=${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}} -DKEYCLOAK_URL=${{secrets.KEYCLOAK_URL}}/realms/${{secrets.KEYCLOAK_REALM}}/protocol/openid-connect/token -DBASE_URI=${{secrets.BASE_URI}} -DBROWSER=${{secrets.BROWSER}} -DENV=${{secrets.ENV}} -f tests/pom.xml

      # Upload Spark report for debugging purposes
      - name: Upload Spark report for debugging purposes
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-spark-report
          path: ./tests/test-output/extent/Spark/Index.html

      # Upload Cucumber JSON for debugging purposes
      - name: Upload Cucumber JSON for debugging purposes
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-json-report
          path: ./tests/target/cucumber-reports/CucumberTestReport.json
