name: Generate/Upload all Coverage Reports

on:
  push:
    branches: [tests/documentation]

jobs:
  cucumber-tests:

    name: Runs cucumber-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install chromium driver
        run: sudo apt-get -yqq install chromium-chromedriver

      # Get Code Climate binary
      - name: build docker and run tests
        run: docker-compose up -d && mvn verify -f tests/pom.xml
