name: Docker Image CI

on:
  workflow_dispatch:
    branches: [master, akroon3r-patch-1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Login to Openshift Docker
        run : |
          docker login docker-registry.pathfinder.gov.bc.ca -u $(oc whoami) -p ${{ secrets.OPENSHIFT_SA_PASSWORD }}

      - name: Build the Docker image
        run: |          
          
          docker-compose build efiling-demo
          
          docker tag jag-file-submission_efiling-demo ${{ secrets.DOCKERHUB_ORG }}/efiling-admin:latest                     
          docker push ${{ secrets.DOCKERHUB_ORG }}/efiling-admin
          
          docker tag jag-file-submission_efiling-demo ${{ secrets.OPENSHIFT_INTERNAL_REGISTRY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/efiling-admin-test:latest
          docker push ${{ secrets.OPENSHIFT_INTERNAL_REGISTRY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/efiling-admin-test:latest
