name: Build Docker

on:
  pull_request:
    branches: [master]

jobs:
  docker-build:
    name: Ensure Docker Builds Without Error
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      # Build Docker and Run Tests
      - name: build docker
        run: |
          docker-compose build efiling-api efiling-demo efiling-frontend efiling-graphql
