name: Build Docker

on:
  pull_request:
    branches: [master]

jobs:
  docker-build:
    name: Ensure Docker Builds Without Error
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build Docker and Run Tests
      - name: build docker
        run: |
          EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET=${{secrets.EFILING_DEMO_KEYCLOAK_CREDENTIALS_SECRET}} KEYCLOAK_REALM=${{secrets.KEYCLOAK_REALM}} KEYCLOAK_URL=${{secrets.KEYCLOAK_URL}} EFILING_DEMO_KEYCLOAK_REALM=${{secrets.EFILING_DEMO_KEYCLOAK_REALM}} EFILING_DEMO_KEYCLOAK_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} KEYCLOAK_AUTH_SERVER_URL=${{secrets.EFILING_DEMO_KEYCLOAK_URL}} docker-compose up -d redis sftp clamav efiling-api keycloak efiling-demo efiling-frontend
 
